---
- name: manage backend configuration
  become: true
  hosts: localhost
  tasks:
    - name: get variables
      include_vars:
        file: _variables.yml
        name: variables

    - name: remove pool
      include: tasks/tasks_f5_pool_delete

    - name: remove docker container
      include: tasks/tasks_docker_container_delete

    - name: remove docker image
      include: tasks/tasks_docker_image_delete
